"""init

Revision ID: e89b5053fa82
Revises:
Create Date: 2026-10-01 15:07:48.716844

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e89b5053fa82"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = sa.Enum("TEACHER", "STUDENT", "ADMIN", name="role")
    role_enum.create(op.get_bind())
    op.add_column(
        "users",
        sa.Column(
            "full_name", sa.String(length=100), server_default="Гость", nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "role", sa.Enum("TEACHER", "STUDENT", "ADMIN", name="role"), nullable=False
        ),
    )
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "name",
            sa.VARCHAR(length=100),
            server_default=sa.text("'Гость'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "role")
    op.drop_column("users", "full_name")
    role_enum = sa.Enum(name="role")
    role_enum.drop(op.get_bind())
    # ### end Alembic commands ###
